language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - nightly
  # - pypy

install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip pytest pytest-flake8 pytest-cov coveralls
  - pip install -e client
  - pip install -e server
  - pip install -e pytest_wdb

script: py.test server/wdb_server/ client/wdb test pytest_wdb --flake8 --cov-report= --cov=client/wdb --cov=test --cov-config=.coveragerc

after_success: coveralls

sudo: false
